name: untitled3 # Your project name
description: "A simple, modern Money Target Tracker Android app built with Flutter."
publish_to: 'none' # Prevents accidental publishing

version: 1.0.0+1

environment:
  sdk: '>=3.6.1 <4.0.0' # Adjust based on your Flutter SDK version

dependencies:
  flutter:
    sdk: flutter

  # UI and Core Utilities
  cupertino_icons: ^1.0.8 # Standard iOS style icons
  intl: ^0.19.0 # For date and time formatting (e.g., in history list)
  provider: ^6.0.5 # For state management (MoneyTrackerProvider)
  currency_text_input_formatter: ^2.1.10 # Optional: For better currency input field formatting

  # Data Persistence
  shared_preferences: ^2.2.2 # For simple key-value storage (monthly target)
  hive: ^2.2.3 # Fast, lightweight, NoSQL database for structured data (income entries)
  hive_flutter: ^1.1.0 # Flutter integration for Hive

  # (Keeping other dependencies from your provided pubspec for completeness,
  # though they are not strictly needed for the Money Target Tracker functionality)
  google_fonts: ^6.1.0
  sms_flutter_plus: ^1.0.0
  flutter_quill: ^11.4.0
  flutter_quill_extensions: ^11.0.0
  flutter_background_service: ^5.0.1
  http: ^1.3.0
  image_picker: ^1.1.2
  file_picker: ^8.0.0+1
  dotted_border: ^2.1.0
  percent_indicator: ^4.2.2
  fl_chart: ^0.71.0
  excel: ^4.0.6
  pdf: ^3.10.4
  printing: ^5.12.0
  path_provider: ^2.1.1
  permission_handler: ^12.0.0+1
  table_calendar: ^3.0.9
  flutter_svg: ^2.0.9
  flutter_screenutil: ^5.9.0
  url_launcher: ^6.1.14
  flutter_otp_text_field: ^1.1.0+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0 # Linting rules for clean code

  # Code Generation for Hive
  build_runner: ^2.4.6   # Tool to run code generators (like hive_generator)
  hive_generator: ^2.0.1 # Generates Hive adapters based on annotations

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/fonts/

  fonts:
    - family: Arial
      fonts:
        - asset: assets/fonts/arial_regular.ttf
          weight: 200
        - asset: assets/fonts/arial_bold.ttf
          weight: 700

    - family: Poppins
      fonts:
        - asset: assets/fonts/poppins_semibold.ttf
          weight: 600

    - family: Pacifico
      fonts:
        - asset: assets/fonts/pacifico_regular.ttf
          weight: 200

    - family: MyFlutterApp
      fonts:
        - asset: assets/fonts/MyFlutterApp.ttf
